name: 'Execution Agendada'

on:
  schedule:
    - cron: '0 0 * * 6'  
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: npm run test:e2e